### ISSUE TITLE
Problem installing from PyPI

### ISSUE THREAD

**Issue by murphyke** [jgehrcke/timegaps#1]
$ pip install timegaps
Downloading/unpacking timegaps
  Downloading timegaps-0.1.0.zip (40kB): 40kB downloaded
  Running setup.py (path:/private/var/folders/b6/7mmmgl3x71bd8d9t_ts2g2ldcrykkj/T/pip_build_murphyke/timegaps/setup.py) egg_info for package timegaps
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/private/var/folders/b6/7mmmgl3x71bd8d9t_ts2g2ldcrykkj/T/pip_build_murphyke/timegaps/setup.py", line 28, in <module>
        long_description=open("README.rst", "rb").read().decode('utf-8'),
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/private/var/folders/b6/7mmmgl3x71bd8d9t_ts2g2ldcrykkj/T/pip_build_murphyke/timegaps/setup.py", line 28, in <module>

```
long_description=open("README.rst", "rb").read().decode('utf-8'),
```

IOError: [Errno 2] No such file or directory: 'README.rst'

**Comment by jgehrcke** [comment]
Thanks for letting me know. I can reproduce and will look into it 
(obviously I tested the build before, so I am quite surprised).

**Comment by jgehrcke** [comment]
Another difference between former setuptools and distutils seems to have tricked me. In another (older) project of mine, the README.rst was included automatically in the source distribution. With pure modern distutils this does not happen:

https://mail.python.org/pipermail/distutils-sig/2013-November/023111.html

Travis CI does not test for this, since it executes `install` right within the repo. I will modify the manifest file correspondingly. Thanks for letting me know, and congrats for obviously being the first user of timegaps except for me.

**Comment by jgehrcke** [comment]
timegaps 0.1.1 is released via PyPI. It resolves this issue. Thanks again, and please let me know how timegaps works out for you.

**Comment by murphyke** [comment]
Thanks for the responsiveness (although I had already installed it via manual install).  I'll let you know how it goes.
