### ISSUE TITLE
Confusing error message about codec

### ISSUE THREAD

**Issue by murphyke** [jgehrcke/timegaps#2]
I ran timegaps in a crontab, and the stripped-down environment caused timegaps to emit this error message:

```
ERROR: Please explicitly specify the codec that should be used for decoding data read from stdin, and for encoding data that is to be written to stdout: set environment variable PYTHONIOENCODING. Example: export PYTHONIOENCODING=UTF-8.
```

I am up and running by defining `PYTHONIOENCODING` for the crontab timegaps command.

However, I found the error confusing because it referred to stdout and stdin and made me wonder if timegaps was not seeing the file arguments and silently attempting to default to stdin mode.  Apologies if you find such a terrible speculation insulting ;-)

Maybe the message could be modified to indicate that the codec is also used for command line processing, if that is what is happening.  Unless the user has specified `--stdin`, there's no need to mention it in the error message, but I would understand if you wanted to have a one-size-fits-all error message.

**Comment by jgehrcke** [comment]
Thanks for the feedback again.

**A little background on this**
Timegaps almost always needs to write something to `stdout`. Since `stdout` is a byte stream, Python needs to encode unicode data before it writes it to `stdout`. But which codec do we use for this? The goal is that the receiving end understands the encoded data. Python automatically determines the codec  based on the value of the `LC_CTYPE` environment variable, but _only if `stdout` is a tty_, i.e. when stdout is displayed to the user in a terminal. If the program is not run in an interactive shell or if the output is piped to another process,  the output encoding is not defined, i.e. `sys.stdout.encoding` is `None`. In this case, we (the timegaps program) can make an educated guess or leave the decision up to the user. Educated guesses with respect to encoding in my opinion, and in opinion of others, are a quite mean source of error, whereas a clear request to the user to choose the right encoding for his/her system is the only way to achieve reliability of the software itself. Relying on the user-given environment variable `PYTHONIOENCODING` therefore is a reasonable choice. This opinion is shared for example here: http://stackoverflow.com/a/4374457/145400 and here: http://stackoverflow.com/a/6361471/145400

**Your case**
Now it should be clear that in your case the encoding to be used for writing to `stdout` was unclear to the program, because you ran timegaps non-interactively as a cron job.

The error message has nothing to do with command line argument parsing, because luckily there is a generic solution (I think) to this problem, which is implemented in timegaps. Since the error message does not mention command line arguments, I think this should not be an issue.

Since mentioning `stdin` in the error message confused you, we could implement two different error messages:
- If `stdin` is not used at all, then the error message should only say that timegaps does not know how to write data to `stdout`.
- If `stdin` is used, then the error message should say that timegaps does neither know how to read from `stdin`, nor does it know how to write to `stdout`.

Does this make sense or is it still too user unfriendly?:)

**Comment by murphyke** [comment]
Yes, that makes perfect sense, thanks!
